### ISSUE TITLE
Issue when new monitor added

### ISSUE THREAD

**Issue by mouncy** [lennart-k/gnome-rounded-corners#13]
When a monitor with a resolution different from those already present is added, the corners are not updated.
I don't think this error is distribution dependent as I haven't seen monitor handling in the code. However my OS is Ubuntu 21.10 with GNOME 40, but it also happened on Ubuntu 21.04 with GNOME 38.

**Comment by PhilDevProg** [comment]
Same on GNOME 41, Fedora 35.

**Comment by lennart-k** [comment]
Hey, with a new version which is currently waiting for review this issue should be fixed. :)
If not feel free to reopen the issue.
