### ISSUE TITLE
Add multi-monitor support

### ISSUE THREAD

**Issue by ExposedCat** [lennart-k/gnome-rounded-corners#16]
Do not round corners between 2 displays and/or add setting to choose what corners should be rounded for each monitor.
![image](https://user-images.githubusercontent.com/44642024/147149158-0a8c12a9-0064-4b25-bc54-24d097e6997f.png)

**Comment by lennart-k** [comment]
Sorry, I'm currently not really willing to put too much time into that feature as that would imply making a proper configuration menu, but feel free to make a pull request.
