### ISSUE TITLE
Round corners in fullscreen mode

### ISSUE THREAD

**Issue by ExposedCat** [lennart-k/gnome-rounded-corners#17]
Move "rounded corners" to first "layer" after opening app in fullscreen mode (100% of screen) so that this action will not remove them

**Comment by lennart-k** [comment]
Sorry, I'm not able to reproduce that issue. Do you know which layer would be higher or are you perhaps talking about a fullscreen mode where only the app has control over the display?

**Comment by ExposedCat** [comment]
@lennart-k idk exactly, but you can try Visual Studio Code to reproduce a bug

**Comment by lennart-k** [comment]
Oh, you're right. It's not an issue on X11 but on Wayland. I'll look into this

**Comment by ExposedCat** [comment]
@lennart-k yes, I'm on Wayland. Thank you

**Comment by lennart-k** [comment]
It seems to be an issue with XWayland to be more precise.
For me it works when running VSCode with `--enable-features=UseOzonePlatform --ozone-platform=wayland`

**Comment by ExposedCat** [comment]
@lennart-k same

**Comment by lennart-k** [comment]
It seems to me that there's not really much I can do about it :/
At least I finally know why Dash To Dock is also so broken when VSCode is in fullscreen with XWayland. :D
My hope is that Electron finally makes their Wayland implementation the default.
