### ISSUE TITLE
Console is not defined error

### ISSUE THREAD

**Issue by spxak1** [lennart-k/gnome-rounded-corners#18]
Pop 21.10, 

it worked well until today's update. 

This is what I get: 
![image](https://user-images.githubusercontent.com/29977030/153783987-0db8b6f6-a282-46ef-bf6c-8ba4d37e4b11.png)

The settings open though.

Many thanks for all the work.

**Comment by lennart-k** [comment]
Hey, sorry for the inconvenience and thanks for the info,
I've not been using the proper logging function for GJS which I've now fixed.
The new version is currently waiting for review. :)

**Comment by spxak1** [comment]
Thanks for the quick response and fix!
