### ISSUE TITLE
cannot change settings

### ISSUE THREAD

**Issue by mikoducky** [lennart-k/gnome-rounded-corners#19]
`The settings of extension Rounded_Corners@lennart-k had an error:
```
TypeError: hbox.append is not a function
```

Stack trace:
```
buildPrefsWidget/<@/home/ducky/.local/share/gnome-shell/extensions/Rounded_Corners@lennart-k/prefs.js:42:8
buildPrefsWidget@/home/ducky/.local/share/gnome-shell/extensions/Rounded_Corners@lennart-k/prefs.js:62:4
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
`
Running on Debian 11 with GNOME 3.38.5. It does round corners, but does not allow for any adjustment.

**Comment by lennart-k** [comment]
Should be fixed now, although you maybe have to uninstall and then reinstall it from GNOME Extensions.
The problem was that I'd pushed an update for GNOME 38 which was not actually compatible, now I've disabled it.

**Comment by mikoducky** [comment]
Yup, I can now get to options, but the rounding no longer works. I get an error icon after install.

**Comment by mikoducky** [comment]
ok well never mind. I had to restart and now it all works lol. Thanks!
