### ISSUE TITLE
have corner dodge panel

### ISSUE THREAD

**Issue by ruvaldak** [lennart-k/gnome-rounded-corners#20]
Would love to have the option for the corners to dodge the panel (that is, the top panel in gnome, though I personally have mine on the bottom). As is, with the panel, the corners seem to only apply on the edge that the panel isn't located at (i.e. panel located at the top means rounded corners only apply at the bottom left and bottom right edge). Have the corners be pushed down/up when the panel is visible (so, in a fullscreen app that hides the panel, the corners move back up to the top of the screen).

**Comment by lennart-k** [comment]
Hey, sorry for taking over a year to reply. I don't really have the capacity to implement this, but feel free to submit a pull request if you are still interested. :)
