### ISSUE TITLE
Add support for Gnome 42

### ISSUE THREAD

**Issue by nullnan** [lennart-k/gnome-rounded-corners#21]
This is awesome extensions and I love it. But it shows outdated on Gnome 42 Ubuntu 22.04.
But I try add version "42" to "shell-version" key in metadata.json and installed it. It just works perfectly.
Please consider change it to adapte gnome 42.

**Comment by lennart-k** [comment]
Hey, thanks for testing the extension on GNOME 42. I've just pushed a new version with 42 support in the manifest. :)
