### ISSUE TITLE
bring rounded corners to top

### ISSUE THREAD

**Issue by mikoducky** [lennart-k/gnome-rounded-corners#22]
Having an issue with this extension. More and more programs are beginning to take priority over the rounded corners when full screen. If I focus on Firefox on my second monitor, rounded corners go away, but focusing on a different window brings them back.

**Comment by kcpr** [comment]
I assume that You do have an option "Keep Rounded Corners when Maximized" enabled, right?

**Comment by mikoducky** [comment]
i believe youre thinking of the other rounded extension, rounded window corners, which indeed has that as an option. I do have that selected in the other extension and it works perfectly now. the bonus is that it fixes the windows as well, so these two extensions together do what i want
