### ISSUE TITLE
Additional rounded corner on panel

### ISSUE THREAD

**Issue by JustCryen** [lennart-k/gnome-rounded-corners#24]
Is there a way to add rounded corners to a panel itself?
I think gnome had it in the previous version but it was removed and I was wondering if this extension can fix this.
![image](https://user-images.githubusercontent.com/41633661/177634333-4ce69955-228c-4a02-8473-3246cf2d2971.png)
It would be nice if this option was not mandatory (additional toggle in settings) and since the corner is visible in the overview (which is nice) this would be an additional corner for the screen-wide corner. (not a replacement)
![image](https://user-images.githubusercontent.com/41633661/177634878-02237cd1-a8a4-4187-b548-d0fa1d038a75.png)

**Comment by kcpr** [comment]
You can have it with that extension: https://extensions.gnome.org/extension/4805/panel-corners/ (see the settings if the color will not match your panel one). I think this one does not support it.
