### ISSUE TITLE
Issue with rounded corners using fractional scaling

### ISSUE THREAD

**Issue by andreicozma1** [lennart-k/gnome-rounded-corners#25]
When using dual monitors with fractional scaling (1.25x), the rounded corners look glitched as follows:
![image](https://user-images.githubusercontent.com/14914491/183333357-983f243b-cc61-460e-8f51-03c3faed47ea.png)
Between the monitors at the top looks as such:
![image](https://user-images.githubusercontent.com/14914491/183333385-69838c47-5727-405c-8fa9-c91a10a8e2a7.png)
At the bottom looks at such:
![image](https://user-images.githubusercontent.com/14914491/183333451-ef10c5ac-8c3e-4b4d-a512-f88a2336650a.png)

**Comment by lennart-k** [comment]
Sorry for never responding. Since this is an old issue I'll close it. Feel free to reopen if it still persists.
