### ISSUE TITLE
Gnome 43 support

### ISSUE THREAD

**Issue by oae** [lennart-k/gnome-rounded-corners#27]
Can you add gnome-shell 43 support?

**Comment by lennart-k** [comment]
I'm not using GNOME 43 yet and have some other priorities atm,
but if you could verify that it also works I'll be more than happy to add GNOME 43 to the supported versions. :)

**Comment by oae** [comment]
I have added 43 to `metadata.json`. So far there has been no problem.

**Comment by lennart-k** [comment]
Great, thanks. The new version is now live :)
