### ISSUE TITLE
Not working on Gnome 42.4 Wayland

### ISSUE THREAD

**Issue by s-20** [lennart-k/gnome-rounded-corners#28]
Not sure if it's working on X-11, but I have no rounded corners on my new Nobara 36 (based on Fedora 36) install. I noticed someone else said something on the Gnome Extensions site, so I thought I'd post an issue.

**Comment by lennart-k** [comment]
Hi, I'm also running GNOME 42.4 on Fedora 36 with Wayland and for me it's working fine so I cannot reproduce the issue :/

**Comment by s-20** [comment]
Huh. Okay, sorry to bother you. Maybe it's a weird, I dunno, resolution issue on my end.---

It is far better to grasp the universe as it really is than to persist in delusion, however satisfying and reassuring. 

- Carl Sagan



Oct 7, 2022, 09:27 by ***@***.***:
