### ISSUE TITLE
Fedora 38 released Gnome 44

### ISSUE THREAD

**Issue by martinlindelof** [lennart-k/gnome-rounded-corners#29]
Notification that extension is deprecated, never developed a gnome extension but maybe it's a quick fix to make it compatible with 44?

**Comment by martinlindelof** [comment]
Maybe just add "**44**" in array of shell versions to **metadata.json**

**Comment by ghost** [comment]
I recently upgraded to Fedora 38, which includes the latest version of the Gnome desktop environment (Gnome 44). However, I have encountered an issue where some of the extensions that I had previously installed are no longer working. One such extension is "Rounded Corners" by @lennart-k.

I'm not quite sure what to do about this problem, as I'm not very technically inclined. However, I would like to suggest to extension developers that they consider building their extensions in a way that is more resilient to new updates. This could help prevent issues like the one I'm currently experiencing, and improve the overall user experience for those of us who rely on extensions to customize our desktop environments.

Here is the screenshot: 
![Screenshot from 2023-04-23 15-40-27](https://user-images.githubusercontent.com/83907230/233835069-ff203909-d1ee-4cab-96f2-01da1d06e66e.png)

**Comment by lennart-k** [comment]
Hey, the issue is that in the metadata.json it is stated which Gnome versions are supported and I've yet to add 44.
I can do that today, then it's fixed :)

**Comment by lennart-k** [comment]
Done, you should now be able to update :)

**Comment by ghost** [comment]
Yes. It worked. Thank You
