### ISSUE TITLE
Corners not rounded when focus window is maximized

### ISSUE THREAD

**Issue by Abragus** [lennart-k/gnome-rounded-corners#31]
When the window that is currently in focus is maximized, the corners of the display are not rounded. This applies to most, but not all applications. Corners are rounded in maximized terminal, Steam and Telegram Desktop, but not Firefox, settings, Brave, and most other programs. 

When a system element is in front of the window, the rounded corners return. Examples include: notification, ArcMenu start menu, window switcher (Alt+Tab menu). I tried taking screenshots in different situations, but it turns out the corners were rounded in all of them. My guess is that the screenshot GUI is technically shown briefly when the picture is taken, making the rounded corners return. Activation the screenshot utility does make the rounded corners return. 

Sometimes, there is a delay to the corners disappearing, after entering the maximized application. For example, activating the Alt+Tab menu and then returning to the same application (Firefox, in my case), the rounded corners stay, sometimes for a second or two, but sometimes until clicking the window, or hovering over an element in the application. 

I am running Fedora Workstation 39, Gnome 45.4 with Wayland, kernel 6.7.9-200.fc39.x86_64. Please let me know if there is any other information I can provide to aid in fixing the issue!

**Comment by lennart-k** [comment]
Hey, sorry for taking so long to respond, I didn't have that much time for the last months.
I think this is closely related to #17, in that case I unfortunately have know idea that to do about it. :(
If someone has a fix, feel free to do a PR. :)

**Comment by Abragus** [comment]
The issue seems to be fixed after installing this extension: https://github.com/kazysmaster/gnome-shell-extension-disable-unredirect

Now running Fedora 41 on Gnome 47.
