### ISSUE TITLE
Gnome 46 Support

### ISSUE THREAD

**Issue by RemiZlatinis** [lennart-k/gnome-rounded-corners#32]
Currently, this extension is incompatible with the Gnome 46. 🥲 Are there any plans for future support?

**Comment by lennart-k** [comment]
Hey, thanks for the reminder. I've now been able to find time and verify that the extension is compatible with GNOME 46, so a new compatible version is now submitted and will probably go online very soon.

**Comment by lennart-k** [comment]
It's online now, enjoy!
