### ISSUE TITLE
Not working in Gnome 46.

### ISSUE THREAD

**Issue by mmertgunduz** [lennart-k/gnome-rounded-corners#34]
Hi @lennart-k 

I've downloaded your extension to change borders on my system, but its not changing the border radius of windows.

I'm using Gnome 46, any way or recommendation to fix this issue?

Thanks,

**Comment by erayrafet** [comment]
> Hi @lennart-k
> 
> I've downloaded your extension to change borders on my system, but its not changing the border radius of windows.
> 
> I'm using Gnome 46, any way or recommendation to fix this issue?
> 
> Thanks,

This extension adds rounded borders to the monitor rather, not windows.

**Comment by lennart-k** [comment]
Exactly, there seems to exist this extensions although I've never used it: https://extensions.gnome.org/extension/7048/rounded-window-corners-reborn/

**Comment by erayrafet** [comment]
> Exactly, there seems to exist this extensions although I've never used it: https://extensions.gnome.org/extension/7048/rounded-window-corners-reborn/

I use it. It's nice.
