### ISSUE TITLE
Plans to Update for 3.38?

### ISSUE THREAD

**Issue by perin-lionshead** [lennart-k/gnome-rounded-corners#4]
Hi, this extension just stopped working on 3.38! Do you have any plans to update it? Thanks so much!

**Comment by spxak1** [comment]
Hey there, this worked nicely on 3.36 but it's broken in 3.38. Any plans to fix? Thank you.

**Comment by lennart-k** [comment]
Hey, thanks for the info and sorry for taking so long to respond.
I've just pushed the necessary changes for GNOME 3.38 (almost none :D),
they are currently in review.

**Comment by spxak1** [comment]
> Hey, thanks for the info and sorry for taking so long to respond.
> I've just pushed the necessary changes for GNOME 3.38 (almost none :D),
> they are currently in review.

Thanks for that, in the meantime there was a fix posted which works. Thanks again for your work.

**Comment by lennart-k** [comment]
No worries, the changes have been reviewed on GNOME Extensions so I'll close this issue.
