### ISSUE TITLE
Does not follow screen rotation

### ISSUE THREAD

**Issue by Sceleratis** [lennart-k/gnome-rounded-corners#9]
I'm on a two-in-one laptop (Thinkpad X1 Yoga Gen 4)

I noticed on both Fedora 33 (Gnome 3.whatever) and on Fedora 34 (Gnome 40 using https://github.com/lennart-k/gnome-rounded-corners/pull/8) the bottom rounded corners do not follow screen rotation. If I enter tablet mode (flip the screen back) and rotate the device, the bottom rounded corner overlays just appear half way down the screen instead of at the bottom.

**Comment by lennart-k** [comment]
Hey, after 9 months I've finally found the time to rewrite parts of the extension and make it listen for display changes. This issue should be resolved by the new version which is currently in the review process. :)
